import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/system-overview',
        'architecture/execution-layers',
        'architecture/job-schema',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development/security-guidelines',
        'development/testing-strategy',
      ],
    },
    {
      type: 'category',
      label: 'ADRs',
      link: {
        type: 'generated-index',
        title: 'Architecture Decision Records',
        description: 'Key architectural decisions for the AGEniX ecosystem',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'adr',
        },
      ],
    },
    {
      type: 'category',
      label: 'Zero-Trust',
      items: [
        'zero-trust/zero-trust-execution',
      ],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'roadmap/overview',
        'roadmap/phase-1',
      ],
    },
  ],
};

export default sidebars;
